### ISSUE TITLE
Anonymous caller does not have storage.objects.get access to bringmeaspoon/R2Rdata/R2R_train.json

### ISSUE THREAD

**Issue by winds-line** [Kelym/FAST#1]
When I execute wget https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_train.json -P tasks/R2R/data/, an error will be returned as Anonymous caller does not have storage.objects.get access to bringmeaspoon/R2Rdata/R2R_train.json

**Comment by Kelym** [comment]
Hi, thanks for letting me know! 

The `download.sh` script that gave you this error downloaded the R2R dataset. The script was a copy from [Matterort3DSimulator/tasks/R2R/data/download.sh](https://github.com/peteanderson80/Matterport3DSimulator/blob/master/tasks/R2R/data/download.sh)
Apparently the original repo have updated the download link. I have updated the script as well. Let me know if you have more questions!

**Comment by Kelym** [comment]
I am closing this issue. However if you still have any problem, feel free to re-open it.
